spring:
  config:
    activate:
      on-profile: "${SPRING_PROFILES_ACTIVE:local}"
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:30}
    refresh-expiration-hours: ${JWT_REFRESH_EXPIRATION_HOURS:24}
cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS}
file:
  upload:
    image-dir: ${FILE_UPLOAD_IMAGE_DIR}
    video-dir: ${FILE_UPLOAD_VIDEO_DIR}
    document-dir: ${FILE_UPLOAD_DOCUMENT_DIR}
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG
server:
  use-forward-headers: true
