spring:
  config:
    activate:
      on-profile: release
          
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database: mysql
    show_sql: false  # 운영에서는 false 권장
    hibernate:
      ddl-auto: none
      format_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER_NAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cookie:
  domain: ${COOKIE_DOMAIN}
  secure: ${COOKIE_SECURE}
  path: ${COOKIE_PATH}
  max-age: ${COOKIE_MAX_AGE}
file:
  base-dir: ${FILE_BASE_DIR}
  base-url: ${FILE_BASE_URL}
