spring:
  config:
    activate:
      on-profile: release

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER_NAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379

cookie:
  domain: ${COOKIE_DOMAIN:bokko.kr}
  secure: ${COOKIE_SECURE:true}
  path: ${COOKIE_PATH:/}
  max-age: ${COOKIE_MAX_AGE:1800}

file:
  base-dir: /home/jihoon/borikkori/view/borikkori_view/build/
