name: CI/CD Pipeline

on:
  push:
    # 모든 태그(push → v1.2.3 등)가 대상
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) QEMU & Buildx 세팅 (멀티아키 지원)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3) GHCR 로그인
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: jihoonleee
          password: ${{ secrets.GHCR_TOKEN }}

      # 4) 도커 이미지 빌드 & 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/jihoonleee/borikkori-community:latest
            ghcr.io/jihoonleee/borikkori-community:${{ github.ref_name }}

      # 5) SSH 준비
      - name: Prepare SSH directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Populate known_hosts
        run: |
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Add SSH key to agent
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no deploy@bokko.kr "echo 'SSH 연결 성공'"

      # 6) 서버에 배포
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: bokko.kr
          port: 22
          username: deploy
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e

            IMAGE=ghcr.io/jihoonleee/borikkori-community:latest

            echo "🔐 GHCR 로그인"
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u jihoonleee --password-stdin

            echo "⬇️ 새 이미지 Pull: $IMAGE"
            docker pull $IMAGE

            # 환경변수 복호화
            cd ~/borikkori/secret
            gpg --batch --yes \
              --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
              --decrypt .env.release.gpg > .env.release
            chmod 600 .env.release

            # docker-compose로 재배포
            cd ~/borikkori/api/borikkori_api
            export ENV_FILE=~/borikkori/secret/.env.release
            docker-compose -f docker-compose.release.yml --env-file $ENV_FILE pull
            docker-compose -f docker-compose.release.yml --env-file $ENV_FILE up -d
            docker-compose -f docker-compose.release.yml --env-file $ENV_FILE ps

            # 민감정보 정리
            rm ~/borikkori/secret/.env.release
