name: WagWagT CI

on:
  push:
    branches:
      - master  # Change to the default branch name of your repository
  pull_request:
    branches:
      - master  # Change to the default branch name of your repository

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - run: echo ${{ github.workspace }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
