name: WagWagT CI

on:
  push:
    branches:
      - main  # Change to the default branch name of your repository
  pull_request:
    branches:
      - main  # Change to the default branch name of your repository
env:
  RESOURCE_PATH: /home/runner/work/wagwagt.server/wagwagt.server/src/main/resources/application.yml
  JWT_PATH: /home/runner/work/wagwagt.server/wagwagt.server/src/main/resources/jwt.yml
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        character set server: 'utf8'
        mysql database: ${{ secrets.DB_NAME }}
        mysql user: ${{ secrets.DB_USERNAME }}
        mysql password: ${{ secrets.DB_PASSWORD }}

    - name: Set yml file
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ env.RESOURCE_PATH }} 
      env:
        spring.datasource.url: ${{ secrets.DB_URL }} 
        spring.datasource.username: ${{ secrets.DB_USERNAME }} 
        spring.datasource.password: ${{ secrets.DB_PASSWORD }} 
        spring.mail.host: ${{secrets.MAIL_HOST}}
        spring.mail.port: ${{secrets.MAIL_PORT}}
        spring.mail.username: ${{secrets.MAIL_USERNAME}}
        spring.mail.password: ${{secrets.MAIL_PASSWORD}}
        spring.data.redis.host: ${{secrets.REDIS_HOST}}
        spring.data.redis.port: ${{secrets.REDIS_PORT}}
        
    - name: Set jwt yml file 
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ env.JWT_PATH }} 
      env:
        secret-key: ${{ secrets.JWT_KEY }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Build with Gradle
      run: ./gradlew build

